Auto tagger api
EdgeTier/WatchTower-Auto-Tagger pull request #2
Opened 2024-09-10 13:36 UTC by vpaidimu

converted this to API

2024-09-13 15:17 UTC, paulminogue requested changes
Just a few changes here. Happy to discuss in more detail on Monday. One thing also, where do we load in the transformer? (maybe I missed it)

2024-09-13 15:25 UTC, vpaidimu commented on alembic/env.py
> +database_url = "postgresql://postgres:pass123@localhost:5432/production"
yeah it should, will change this. don't think I committed it.

2024-09-13 15:26 UTC, vpaidimu commented on alembic/versions/0ee7b722fe8a_initial_commit.py
> +"""Initial commit
sure!

2024-09-13 15:28 UTC, vpaidimu commented on alembic/versions/1baee7b7b8b1_add_create_date_time_last_modified_.py
> +def upgrade() -> None:
I just included everything alembic generated so far, may be we don't need to include all the migrations. it could be a file generated accidentally.

2024-09-13 15:31 UTC, vpaidimu commented on alembic/versions/73259ce59624_added_create_date_time_modified_.py
> +        unique=False,
I have the `client_id` indexed, just need to add another migration.

2024-09-13 15:33 UTC, vpaidimu commented on data_processing/create_llm_template.py
> +    for message in messages:
Done.

2024-09-13 15:34 UTC, vpaidimu commented on data_processing/create_llm_template.py
> +        actual_message = message.message.replace("\n", " ")
yeah like footers with long T&C like Belmond ones. What will be the ideal length of message?

2024-09-13 15:36 UTC, vpaidimu commented on data_processing/create_llm_template.py
> +    except Exception:
don't think there is any difference, but I tend to use filter for joins and where for conditions to kind of keep them neat and tidy.

2024-09-13 15:37 UTC, vpaidimu commented on database/prompts.py
> +    prompt = Column(String)
Will do.

2024-09-13 15:37 UTC, vpaidimu commented on handlers/handle_auto_tagging_task.py
> +            f"than 2 or customer messages count less than 2"
need to update the warning! I actually don't check for that at all.

2024-09-13 15:37 UTC, vpaidimu commented on requirements.txt
> +transformers==4.44.2
cool, will take a look

2024-09-13 15:41 UTC, vpaidimu commented
The model is in the `rag_service.py`

2024-09-16 13:11 UTC, vpaidimu commented on data_processing/create_llm_template.py
> +    prompt_task = "classification_" if classification else "summary_"
Done.

2024-10-01 18:08 UTC, merged